### ISSUE TITLE
Deploy job completed successfully, but it doesn't reflect in the production? 

### ISSUE THREAD

**Issue by 0xsirsaif** [0xsirsaif/text-summ-app#1]
Details later

**Comment by 0xsirsaif** [comment]
![Release step in the deploy job](https://user-images.githubusercontent.com/55336614/180644185-65f87ae8-b8b0-4539-9c08-f4bf540e687f.png)

**Comment by 0xsirsaif** [comment]
Now, the last two steps in the deploy job: Setting env vars, and Release using `release.sh` script are:
```yml
- name: Set environment variables
  run: |
    echo "HEROKU_REGISTRY_IMAGE=${{ env.HEROKU_REGISTRY_IMAGE }}" >> $GITHUB_ENV
    echo "HEROKU_AUTH_SECRET=${{ secrets.HEROKU_AUTH_SECRET }}" >> $GITHUB_ENV
- name: Release
  run: bash release.sh
```
and the `release.sh` is:

```bash
#!/bin/sh

set -e

# shellcheck disable=SC1083
IMAGE_ID=$(docker inspect "${HEROKU_REGISTRY_IMAGE}" --format={{.Id}})
echo IMAGE_ID

PAYLOAD='{"updates": [{"type": "web", "docker_image": "'"$IMAGE_ID"'"}]}'
echo PAYLOAD

curl -n -X PATCH https://api.heroku.com/apps/"$HEROKU_APP_NAME"/formation \
  -d "${PAYLOAD}" \
  -H "Content-Type: application/json" \
  -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
  -H "Authorization: Bearer ${HEROKU_AUTH_SECRET}"
```
The broken version of them was:
```yml
- name: Set environment variables
  run: |
    echo "HEROKU_REGISTRY_IMAGE=${{ env.HEROKU_REGISTRY_IMAGE }}" >> $GITHUB_ENV
    echo "HEROKU_AUTH_SECRET=${{ secrets.HEROKU_AUTH_SECRET }}" >> $GITHUB_ENV
- name: Release
  run: |
    chown +x release.sh
    ./release.sh
```
and the `release.sh` is:

```bash
#!/bin/sh

set -e

# shellcheck disable=SC1083
IMAGE_ID=$(docker inspect "${HEROKU_REGISTRY_IMAGE}" --format={{.Id}})
echo IMAGE_ID

PAYLOAD='{"updates": [{"type": "web", "docker_image": "'"$IMAGE_ID"'"}]}'
echo PAYLOAD

curl -n -X PATCH https://api.heroku.com/apps/"$HEROKU_APP_NAME"/formation \
  -d "${PAYLOAD}" \
  -H "Content-Type: application/json" \
  -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
  -H "Authorization: Bearer ${HEROKU_AUTH_**TOKEN**}"
```
